# Generated by Django 5.2 on 2025-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Base_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="Image",
            field=models.ImageField(blank=True, upload_to="Items/"),
        ),
    ]
