# Generated by Django 5.2 on 2025-05-16 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Base_app", "0004_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Base_app.items"
            ),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
