# Generated by Django 5.2 on 2025-05-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Base_app", "0005_alter_cart_product_delete_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.CharField(max_length=255),
        ),
    ]
