# Generated by Django 5.2 on 2025-05-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Base_app", "0007_order"),
    ]

    operations = []
