# Generated by Django 5.2 on 2025-05-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Base_app", "0008_auto_20250521_1915"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
