# Generated by Django 5.2 on 2025-05-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Base_app", "0011_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
